### ISSUE TITLE
Error:can`t find client.js

### ISSUE THREAD

**Issue by xianengzhi** [xiaohuoni/malita#2]
<img width="611" alt="image" src="https://user-images.githubusercontent.com/25165311/189259092-33ac7464-b6d6-4339-9b1d-c1cfc3a8eba6.png">

**Comment by xiaohuoni** [comment]
要看你服务启用的端口号

**Comment by xianengzhi** [comment]
> 要看你服务启用的端口号

是我没有运行 `build:client` 导致的，不是说注入客户端的ws代码可以写到 `esbuid` 的 `plugins` 里去么，这一步后来没有实现么？

**Comment by xiaohuoni** [comment]
可能没有吧，看文章，我也记不清了
